import React, { useMemo, useState } from "react";
import { View, StyleSheet } from "react-native";
import { Card, Text, TextInput, Button, Divider } from "react-native-paper";

type Props = {
  scanId: string;
  // keep loose types so it never breaks build in hurry
  violations?: any[];
  extractedFields?: any[];
};

function safeStr(v: any) {
  return typeof v === "string" ? v : v == null ? "" : String(v);
}

function getField(extractedFields: any[] | undefined, keys: string[]) {
  if (!Array.isArray(extractedFields)) return "";
  const lowerKeys = keys.map((k) => k.toLowerCase());
  for (const f of extractedFields) {
    const name =
      safeStr(f?.name || f?.field || f?.key || f?.label || f?.type).toLowerCase();
    const value = safeStr(f?.value || f?.text || f?.extractedText);
    if (!name || !value) continue;
    if (lowerKeys.some((k) => name.includes(k))) return value;
  }
  return "";
}

function violationsToBullets(violations: any[] | undefined) {
  if (!Array.isArray(violations) || violations.length === 0) return ["No violations detected by system."];
  return violations.map((v, i) => {
    const title = safeStr(v?.title || v?.code || v?.type || `Violation ${i + 1}`);
    const msg = safeStr(v?.message || v?.detail || v?.description || "");
    const rule = safeStr(v?.rule || v?.ruleCitation || v?.ruleRef || "");
    const sev = safeStr(v?.severity || "").toUpperCase();
    const parts = [
      `${i + 1}. ${title}${sev ? ` [${sev}]` : ""}`,
      msg ? `   - ${msg}` : "",
      rule ? `   - Rule: ${rule}` : "",
    ].filter(Boolean);
    return parts.join("\n");
  });
}

export default function ComplaintGeneratorCard({ scanId, violations, extractedFields }: Props) {
  const [name, setName] = useState("");
  const [contact, setContact] = useState("");
  const [location, setLocation] = useState("");
  const [seller, setSeller] = useState("");
  const [product, setProduct] = useState("");
  const [extra, setExtra] = useState("");

  const autoProduct = useMemo(() => {
    const p =
      getField(extractedFields, ["product", "commodity", "item"]) ||
      getField(extractedFields, ["brand"]);
    return p;
  }, [extractedFields]);

  const bullets = useMemo(() => violationsToBullets(violations), [violations]);

  const draft = useMemo(() => {
    const prodLine = (product || autoProduct) ? `Product/Packaged Item: ${product || autoProduct}\n` : "";
    const sellerLine = seller ? `Seller/Outlet: ${seller}\n` : "";
    const locLine = location ? `Location: ${location}\n` : "";
    const personLine =
      (name || contact)
        ? `Complainant: ${name || "________"}\nContact: ${contact || "________"}\n`
        : "";

    const findingBlock = bullets.map((b) => `- ${b.replace(/\n/g, "\n  ")}`).join("\n");

    return (
`To,
The Legal Metrology Officer / Controller
(Concerned Jurisdiction)

Subject: Complaint regarding non-compliance in packaged commodity labeling (Legal Metrology)

Respected Sir/Madam,

I request you to kindly take necessary action regarding a packaged commodity that appears non-compliant as per Legal Metrology (Packaged Commodities) Rules.

${personLine}${locLine}${prodLine}${sellerLine}
System Scan Reference ID: ${scanId}

Observed findings/violations:
${findingBlock}

Additional notes (optional):
${extra || "-"}

Evidence:
- Images and scan report generated by the system for Scan ID ${scanId}

Kindly register this complaint and initiate inspection/action as per applicable rules.

Sincerely,
${name || "________"}
Date: __________
`
    );
  }, [scanId, name, contact, location, seller, product, autoProduct, bullets, extra]);

  const copyDraft = async () => {
    try {
      // web
      // @ts-ignore
      if (typeof navigator !== "undefined" && navigator?.clipboard?.writeText) {
        // @ts-ignore
        await navigator.clipboard.writeText(draft);
        return;
      }
      alert("Copy not supported in this environment. Please select and copy manually.");
    } catch {
      alert("Copy failed. Please select and copy manually.");
    }
  };

  const downloadTxt = () => {
    try {
      // web only
      // @ts-ignore
      if (typeof window === "undefined") return;
      const blob = new Blob([draft], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `complaint_${scanId}.txt`;
      a.click();
      setTimeout(() => URL.revokeObjectURL(url), 500);
    } catch {
      alert("Download not supported. Please copy the text.");
    }
  };

  return (
    <Card style={styles.card}>
      <Card.Title title="Create Complaint" subtitle="Auto-generate a complaint draft from findings" />
      <Card.Content>
        <View style={styles.row}>
          <TextInput style={styles.half} label="Your Name" value={name} onChangeText={setName} />
          <TextInput style={styles.half} label="Contact (phone/email)" value={contact} onChangeText={setContact} />
        </View>

        <View style={styles.row}>
          <TextInput style={styles.half} label="Location (City/State)" value={location} onChangeText={setLocation} />
          <TextInput style={styles.half} label="Seller/Shop (optional)" value={seller} onChangeText={setSeller} />
        </View>

        <TextInput
          label="Product/Brand (optional)"
          value={product}
          onChangeText={setProduct}
          placeholder={autoProduct ? `Auto: ${autoProduct}` : "Enter product name"}
          style={{ marginTop: 10 }}
        />

        <TextInput
          label="Extra notes (optional)"
          value={extra}
          onChangeText={setExtra}
          multiline
          numberOfLines={2}
          style={{ marginTop: 10 }}
        />

        <Divider style={{ marginVertical: 12 }} />

        <Text variant="titleMedium">Complaint Draft</Text>
        <TextInput value={draft} multiline numberOfLines={14} style={{ marginTop: 8 }} />

        <View style={styles.btnRow}>
          <Button mode="outlined" onPress={copyDraft}>Copy</Button>
          <Button mode="contained" onPress={downloadTxt}>Download .txt</Button>
        </View>
      </Card.Content>
    </Card>
  );
}

const styles = StyleSheet.create({
  card: { marginTop: 12 },
  row: { flexDirection: "row", gap: 10 },
  half: { flex: 1, marginTop: 8 },
  btnRow: { flexDirection: "row", gap: 10, marginTop: 12, justifyContent: "flex-end" },
});
